project:
  type: website
  output-dir: .

website:
  title: "Deep Learning Utilities" # Title of the website
  navbar:
    collapse-below: lg
    pinned: true
    right:
      - id: intro
        text: "Introduction"
        href: index.qmd
        
      - text: "Tutorials"
        menu:
          - text: "Training a keypoint detector"
            
      - text: "How-to guides"
        menu:
          - text: "Installation"
            href: how_to_guides/installation.qmd
            
      - text: "Reference Guides"
        menu:
          - text: "User Guide"
            href: user_guide/index.qmd
                
      - text: "Concepts"

  sidebar:
    - title: "User Guide"
      style: "docked"
      collapse-level: 1
      contents:
        - text: "Introduction"
          href: user_guide/index.qmd
        - section: "Data Types"
          href: user_guide/data_types/index.qmd
          contents:
            - user_guide/data_types/keypoints.qmd
        - section: "Labels"
          href: user_guide/labels/index.qmd
          contents:
            - user_guide/labels/keypoint_labels.qmd
            - user_guide/labels/segmentation_labels.qmd
            - user_guide/labels/line_labels.qmd
        - section: "Layers"
          href: user_guide/layers/index.qmd
          contents:
            - user_guide/layers/Blur2D.qmd
            - user_guide/layers/mask_encoder.qmd
            - user_guide/layers/sequential_coattention.qmd
        - section: "Models"
          href: user_guide/models/index.qmd
          contents:
            - user_guide/models/keypoint_detector.qmd
            - user_guide/models/segmentation_model.qmd
            - user_guide/models/line_model.qmd

format:
  html:
    theme: github-dark
    smooth-scroll: true
    css: styles.css
    toc: true

editor: visual

