name: Import DeepLearningUtils

on: [push, pull_request]

jobs:
  import-script:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install DeepLearningUtils with TensorFlow
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tensorflow]

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

    - name: Run import script
      run: |
        cd ..
        echo "import DeepLearningUtils" > import_script.py
        python import_script.py